-- MySQL Script generated by MySQL Workbench
-- 03/27/23 01:59:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cs_go_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cs_go_db` ;

-- -----------------------------------------------------
-- Schema cs_go_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cs_go_db` DEFAULT CHARACTER SET utf8 ;
USE `cs_go_db` ;

-- -----------------------------------------------------
-- Table `cs_go_db`.`MEMBERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs_go_db`.`MEMBERS` ;

CREATE TABLE IF NOT EXISTS `cs_go_db`.`MEMBERS` (
  `membersID` INT NULL AUTO_INCREMENT,
  `Player1`   VARCHAR(45) NOT NULL,
  `Player2`   VARCHAR(45) NOT NULL,
  `Player3`   VARCHAR(45) NOT NULL,
  `Player4`   VARCHAR(45) NOT NULL,
  `Player5`   VARCHAR(45) NOT NULL,
  PRIMARY KEY (`membersID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cs_go_db`.`TEAMS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs_go_db`.`TEAMS` ;

CREATE TABLE IF NOT EXISTS `cs_go_db`.`TEAMS` (
  `teamsID`   INT NULL AUTO_INCREMENT,
  `name` 	  VARCHAR(45) NOT NULL,
  `coach` 	  VARCHAR(45) NOT NULL,
  `membersID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`teamsID`))
  FOREIGN KEY (`membersID`) REFERENCES MEMBERS(`membersID`)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cs_go_db`.`MATCHES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs_go_db`.`MATCHES` ;

CREATE TABLE IF NOT EXISTS `cs_go_db`.`MATCHES` (
  `matchID` 	  INT NOT NULL AUTO_INCREMENT,
  `TeamID1` 	  INT NOT NULL,
  `TeamID2` 	  INT NOT NULL,
  `age` 		  INT NOT NULL,
  `tournamentsID` INT NOT NULL,
  `winner` 		  INT NOT NULL,
  PRIMARY KEY (`matchID`))
  FOREIGN KEY (`teamID1`) REFERENCES TEAMS(`teamsID`)
  FOREIGN KEY (`teamID2`) REFERENCES TEAMS(`teamsID`)
  FOREIGN KEY (`winner`) REFERENCES TEAMS(`teamsID`)
  FOREIGN KEY (`tournamentsID`) REFERENCES TOURNAMENTS(`tournamentsID`)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cs_go_db`.`CIRCUITPOINT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs_go_db`.`CIRCUITPOINT` ;

CREATE TABLE IF NOT EXISTS `cs_go_db`.`CIRCUITPOINT` (
  `circuitPointID`  INT NOT NULL AUTO_INCREMENT,
  `place` 			VARCHAR(45) NOT NULL,
  `usd` 			DOUBLE NOT NULL,
  `points` 			DOUBLE NOT NULL,
  PRIMARY KEY (`circuitPointID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cs_go_db`.`PLAYOFFS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs_go_db`.`PLAYOFFS` ;

CREATE TABLE IF NOT EXISTS `cs_go_db`,`PLAYOFFS` (
	`playoffsID` INT NOT NULL AUTO_INCREMENT,
	`phase`      VARCHAR2 NOT NULL,
	`matchID` 	 INT NOT NULL,
  PRIMARY KEY (`playoffsID`)
  FOREIGN KEY (`matchID`) REFERENCES MATCHES(`matchID`)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cs_go_db`.`GROUPSTAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs_go_db`.`GROUPSTAGE` ;

CREATE TABLE IF NOT EXISTS `cs_go_db`.`GROUPSTAGE` (
  `groupStageID` INT NOT NULL AUTO_INCREMENT,
  `groupID1` INT NOT NULL,
  `groupID2` INT NOT NULL,
  `groupID3` INT NOT NULL,
  `groupID4` INT NOT NULL,
  PRIMARY KEY (`groupStageID`))
  FOREIGN KEY (`groupID1`) REFERENCES GROUPS(`groupID`)
  FOREIGN KEY (`groupID2`) REFERENCES GROUPS(`groupID`)
  FOREIGN KEY (`groupID3`) REFERENCES GROUPS(`groupID`)
  FOREIGN KEY (`groupID4`) REFERENCES GROUPS(`groupID`)
		
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cs_go_db`.`GROUPS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs_go_db`.`GROUPS` ;

CREATE TABLE IF NOT EXISTS `cs_go_db`.`GROUPS` (
  `groupID` INT NOT NULL AUTO_INCREMENT,
  `nameGroup` CHAR NOT NULL,
  `teamID1` INT NOT NULL,
  `teamID2` INT NOT NULL,
  `teamID3` INT NOT NULL,
  `teamID4` INT NOT NULL,
  `matchID1` INT NOT NULL,
  `matchID2` INT NOT NULL,
  `matchID3` INT NOT NULL,
  `winner` INT NULL,
  PRIMARY KEY (`groupStageID`))
  FOREIGN KEY (`matchID1`) REFERENCES MATCHES(`matchID`)
  FOREIGN KEY (`matchID2`) REFERENCES MATCHES(`matchID`)
  FOREIGN KEY (`matchID3`) REFERENCES MATCHES(`matchID`)
  FOREIGN KEY (`teamID1`) REFERENCES TEAMS(`teamsID`)
  FOREIGN KEY (`teamID2`) REFERENCES TEAMS(`teamsID`)
  FOREIGN KEY (`teamID3`) REFERENCES TEAMS(`teamsID`)
  FOREIGN KEY (`teamID4`) REFERENCES TEAMS(`teamsID`)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cs_go_db`.`TOURNAMENTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs_go_db`.`TOURNAMENTS` ;

CREATE TABLE IF NOT EXISTS `cs_go_db`.`TOURNAMENTS` (
  `tournamentsID` 	INT NOT NULL AUTO_INCREMENT,
  `tournamentsName` VARCHAR(45) NULL),
  `groupStageID` 	INT NOT NULL,
  `playoffsID`		INT NOT NULL, 
  `circuitPointID` 	INT NOT NULL,
  `prizePool` 		DOUBLE NULL,
  `winner` 			INT NOT NULL
  FOREIGN KEY (`groupStageID`) REFERENCES GROUPSTAGE(`groupStageID`)
  FOREIGN KEY (`circuitPointID`) REFERENCES CIRCUITPOINT(`circuitPointID`)
  FOREIGN KEY (`playoffsID`) REFERENCES PLAYOFFS(`playoffsID`)
  FOREIGN KEY (`winner`) REFERENCES TEAMS(`teamsID`)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
